# Generated by Django 5.2.5 on 2025-09-05 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_conducteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['critere__nom'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RemoveConstraint(
            model_name='evaluation',
            name='unique_evaluation',
        ),
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note_evaluation_critere',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='suivi_condu_date_ev_c8c8d8_idx',
            old_name='suivi_conducteurs_evaluation_date_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='suivi_condu_conduct_f44a40_idx',
            old_name='suivi_conducteurs_evaluation_conducteur_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='suivi_condu_type_ev_548d34_idx',
            old_name='suivi_conducteurs_evaluation_type_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='suivi_condu_evaluat_33790e_idx',
            old_name='suivi_conducteurs_note_eval_critere_idx',
        ),
        migrations.RenameIndex(
            model_name='societe',
            new_name='suivi_condu_socnom_7df6b8_idx',
            old_name='suivi_conducteurs_societe_socnom_idx',
        ),
        migrations.AddField(
            model_name='critereevaluation',
            name='numero_ordre',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evaluateur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur Django associé à cet évaluateur', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('conducteur', 'date_evaluation', 'evaluateur', 'type_evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('evaluation', 'critere')},
        ),
    ]
