# Generated by Django 5.2.5 on 2025-08-29 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeEtendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description du groupe')),
                ('couleur', models.CharField(default='#007bff', help_text='Code couleur hexadécimal (ex: #007bff)', max_length=7, verbose_name="Couleur d'affichage")),
                ('niveau_acces', models.IntegerField(default=1, help_text='Plus le nombre est élevé, plus les privilèges sont importants', verbose_name="Niveau d'accès")),
                ('actif', models.BooleanField(default=True, verbose_name='Groupe actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_etendu', to='auth.group')),
            ],
            options={
                'verbose_name': 'Groupe étendu',
                'verbose_name_plural': 'Groupes étendus',
                'ordering': ['-niveau_acces', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGroupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('add_user', 'Ajout utilisateur'), ('remove_user', 'Retrait utilisateur'), ('add_permission', 'Ajout permission'), ('remove_permission', 'Retrait permission')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name="Détails de l'action")),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'action")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='auth.group')),
                ('permission_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission', verbose_name="Permission concernée par l'action")),
                ('utilisateur_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_groupes_cible', to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur concerné par l'action")),
                ('utilisateur_modifieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant effectué la modification')),
            ],
            options={
                'verbose_name': 'Historique des groupes',
                'verbose_name_plural': 'Historiques des groupes',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
